### ISSUE TITLE
Problems with meta_len_tuple

### ISSUE THREAD

**Issue by kondor12** [m13253/midi-track-merge#1]
When i try to use mididump with my track, i see Error:

> NameError: name 'meta_len_tuple' is not defined

We never define 'meta_len_tuple' in code. What does this variable mean?

**Comment by m13253** [comment]
Thank you for using my project!

I think this is due to my mistyping.
I have published a fix, please try it and tell me if it works.

If it still does not work, please email me a sample file so that I can check the problem.

**Comment by kondor12** [comment]
Now it works, thanks)
